### ISSUE TITLE
Add content to README.md

### ISSUE THREAD

**Issue by r-arvind** [r-arvind/opamp-designer#5]
The current readme has a one line description of the tool. It needs more detailed and organized description of the tool.

It need not be too big. The description should be sufficient for people to understand what the designer does

**Comment by gmli-eu** [comment]
I'll update the README.md with a proper template. You can fill it properly afterward.

**Comment by gmli-eu** [comment]
Done #7

**Comment by r-arvind** [comment]
Thanks @MADPT
